solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [LeftEELinear, RightEELinear]
    - [LeftEEAngular, RightEEAngular]

    
constraints: [JointLimits, VelocityLimits]

LeftEE:
    type: Cartesian
    distal_link: arm1_6
    base_link: base_link
    active: true
    name: left_ee

LeftEELinear:
    type: "Subtask"
    task: "LeftEE"
    active: true
    indices: [0, 1, 2]
    
LeftEEAngular:
    type: "Subtask"
    task: "LeftEE"
    active: true
    #lambda: 0.01
    indices: [3, 4, 5]
    #orientation_gain: 1000.0

RightEE:
    type: Cartesian
    distal_link: arm2_6
    base_link: base_link
    active: true
    name: right_ee
    #orientation_gain: 1000.0

RightEELinear:
    type: "Subtask"
    task: "RightEE"
    #weight: 10.0
    #weight: [1., 1., 1.]
    active: true
    indices: [0, 1, 2]
    #orientation_gain: 1000.0
    
RightEEAngular:
    type: "Subtask"
    task: "RightEE"
    active: true
    #lambda: 0.01
    #indices: [3, 4] # 5dof stack
    indices: [3, 4, 5] # 6dof stack
    #orientation_gain: 1000.0

JointLimits:
    type: JointLimits
    bound_scaling: 0.9 # 90% of the specified range
    limits:
        j_arm1_3: [-2.2, -0.2] # 10 deg = 0.174532925
        j_arm2_3: [ 0.2,  2.2]
        j_arm1_6: [-2.7,  2.7]
        j_arm2_6: [-2.7,  2.7]
VelocityLimits:
    type: VelocityLimits
    limits:
        j_arm1_4: 5.0 # 
        j_arm1_5: 3.0 # 
        j_arm1_6: 2.0 # 
        j_arm2_4: 3.0 # 
        j_arm2_5: 3.0 # 2.0 for 5dof
        j_arm2_6: 2.0 # 
