<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="inail2_base" params="rot parent *origin">
        <!-- base -->
        <link name="base_link">
            <inertial>
                <origin xyz="${Base_x} ${rot*Base_y} ${Base_z}" />
                <mass value="${Base_mass}" />
                <inertia ixx="${Base_xx}" ixy="${rot*Base_xy}" ixz="${Base_xz}" iyy="${Base_yy}"
                    iyz="${rot*Base_yz}" izz="${Base_zz}" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://inail2arm_urdf/meshes/mesh_base.stl"
                        scale="0.001 ${rot*0.001} 0.001" />
                </geometry>
                <material name="dark_grey" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://inail2arm_urdf/meshes/simple/mesh_base.stl"
                        scale="0.001 ${rot*0.001} 0.001" />
                </geometry>
            </collision>
        </link>
        <!-- base -->

        <xacro:unless value="${parent == ''}">
            <joint name="base_joint" type="fixed">
                <parent link="${parent}" />
                <child link="base_link" />
                <xacro:insert_block name="origin" />
            </joint>
        </xacro:unless>

    </xacro:macro>

</robot>
